sb_application_name: basic-spring-boot
sb_build_application_display_name: Spring Rest App - Build
sb_build_namespace: basic-spring-boot-build
sb_dev_application_display_name: Spring Rest App - Dev
sb_dev_namespace: basic-spring-boot-dev
sb_stage_application_display_name: Spring Rest App - Stage
sb_stage_namespace: basic-spring-boot-stage
sb_prod_application_display_name: Spring Rest App - Prod
sb_prod_namespace: basic-spring-boot-prod
sb_application_repository_url: "https://github.com/redhat-cop/spring-rest.git"
sb_application_repository_ref: master
sb_application_readiness_response: "status.:.UP"
sb_application_readiness_path: "/health"
sb_sa_name: "jenkins"
sb_source_repository_url: "https://github.com/redhat-cop/container-pipelines.git"
sb_source_repository_ref: master
sb_pipeline_script: "Jenkinsfile"

openshift_cluster_content:
- object: projects
  content:
  - name: apply variables to projects template
    file: "{{ inventory_dir }}/../.openshift/projects/projects.j2"
    action: create
    tags:
      - project
- object: builds
  content:
  - name: "apply variables to build template and deploy build pipeline to dev"
    template: "{{ inventory_dir }}/../.openshift/templates/build.j2"
    action: create
    params_from_vars:
      APPLICATION_NAME: "{{ sb_application_name }}"
      NAMESPACE: "{{ sb_build_namespace }}"
      SOURCE_REPOSITORY_URL: "{{ sb_source_repository_url }}"
      SOURCE_REPOSITORY_REF: "{{ sb_source_repository_ref }}"
      APPLICATION_SOURCE_REPO: "{{ sb_application_repository_url }}"
      APPLICATION_SOURCE_REF: "{{ sb_application_repository_ref }}"
      PIPELINE_SCRIPT: "{{ sb_pipeline_script }}"
    tags:
      - build
- object: deployments
  content:
  - name: "deploy dev environment"
    template: "{{ inventory_dir }}/../.openshift/templates/deployment.yml"
    params_from_vars:
      APPLICATION_NAME: "{{ sb_application_name }}"
      NAMESPACE: "{{ sb_dev_namespace }}"
      SA_NAMESPACE: "{{ sb_build_namespace }}"
      READINESS_RESPONSE: "{{ sb_application_readiness_response }}"
      READINESS_PATH: "{{ sb_application_readiness_path }}"
    tags:
      - deployment
  - name: "deply stage environment"
    template: "{{ inventory_dir }}/../.openshift/templates/deployment.yml"
    params_from_vars:
      APPLICATION_NAME: "{{ sb_application_name }}"
      NAMESPACE: "{{ sb_stage_namespace }}"
      SA_NAME: "{{ sb_sa_name }}"
      SA_NAMESPACE: "{{ sb_build_namespace }}"
      READINESS_RESPONSE: "{{ sb_application_readiness_response }}"
      READINESS_PATH: "{{ sb_application_readiness_path }}"
    tags:
      - deployment
  - name: "deply prod environment"
    template: "{{ inventory_dir }}/../.openshift/templates/deployment.yml"
    params_from_vars:
      APPLICATION_NAME: "{{ sb_application_name }}"
      NAMESPACE: "{{ sb_prod_namespace }}"
      SA_NAME: "{{ sb_sa_name }}"
      SA_NAMESPACE: "{{ sb_build_namespace }}"
      READINESS_RESPONSE: "{{ sb_application_readiness_response }}"
      READINESS_PATH: "{{ sb_application_readiness_path }}"
    tags:
      - deployment
